# Generated by Django 5.0.4 on 2024-04-12 11:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date of event"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="name of event"),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="address of event"),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                "Impossible to create an event with the number of guests less than 1 guest.",
                            )
                        ],
                        verbose_name="number of guests",
                    ),
                ),
                ("notes", models.TextField(verbose_name="notes for the event")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_contract",
                        to="contracts.contract",
                        verbose_name="contract for event",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_employees",
                        to="accounts.employee",
                        verbose_name="employee for event",
                    ),
                ),
            ],
        ),
    ]
